(package "organize-imports-python"
         "0.1.0"
         "Automatically organize imports in Python code")

(website-url "https://github.com/jcs-elpa/organize-imports-python")
(keywords "convenience" "organize" "imports" "python" "eclipse")

(package-file "organize-imports-python.el")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
